default_config:

logger:
  default: info
  logs:
    custom_components.thermal_vision: debug

# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

homeassistant:
  unit_system: metric
  temperature_unit: C
  time_zone: America/Edmonton
  elevation: 1045
  auth_providers:
    - type: homeassistant

sensor:
  - platform: thermal_vision
    name: Thermal Vision Sensor
    host: http://192.168.3.94
    state: person_detected
    scan_interval: 5

binary_sensor:
  - platform: thermal_vision
    name: Thermal Vision Binary Sensor
    host: http://192.168.3.94
    scan_interval: 5

input_text:
  psuedo_pixels:
    name: Pseudo Pixels
    initial: Zl1cXVxdXFtlYF5aXltYWmhgXV5dXFxabGJeXV5eXFprZF1eXF1cXG9lXV5cXFpaamZdXFtbW1tgX15bXVxdXA==

camera:
  - platform: thermal_vision
    name: Thermal Vision Camera
    host: http://192.168.3.94
    scan_interval: 2
    auto_range: true
    mirror: true
    overlay: true
    min_diff: 4

  - platform: thermal_vision
    name: Thermal Vision Camera from ESPHome Sensor
    pixel_sensor: input_text.psuedo_pixels
    auto_range: true
    overlay: true
