default_config:

logger:
  default: info
  logs:
    custom_components.thermal: debug

# If you need to debug uncommment the line below (doc: https://www.home-assistant.io/integrations/debugpy/)
# debugpy:

homeassistant:
  unit_system: metric
  temperature_unit: C
  time_zone: America/Edmonton
  elevation: 1045
  auth_providers:
    - type: homeassistant

sensor:
  - platform: thermal
    name: Prototype Thermal Sensor
    host: http://192.168.3.91

camera:
  - platform: thermal
    name: Prototype Thermal Sensor
    host: http://192.168.3.91
    scan_interval: 2
    auto_range: true
