auto_scale:
  name: "Auto Scale"
  description: "Scale temperature range to current min / max"
  fields:
    entity_id:
      name: "Entity ID"
      description: "Camera or sensor entity id"
      example: camera.thermal_vision
