name: Validate Actions

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  cron-validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v2

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
          ignore: brands wheels hacs

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
