name: Pull actions

on:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    name: Check style formatting
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v3.5.0
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Pull request linter action
        uses: JulienKode/pull-request-name-linter-action@v0.5.0

      - name: Commit Linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: wagoid/commitlint-github-action@v5.1.2

      - uses: actions/setup-python@v4.2.0
        with:
          python-version: "3.x"

      - run: python3 -m pip install black

      - run: black .
