name: Pull actions

on:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    name: Check style formatting
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v3.7.0
        with:
          node-version: 14

      - name: Install dependencies
        run: npm ci

      - name: Pull request linter action
        uses: JulienKode/pull-request-name-linter-action@v0.5.0

      - name: Commit Linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: wagoid/commitlint-github-action@v5.4.1

      - uses: actions/setup-python@v4.7.0
        with:
          python-version: "3.x"

      - run: python3 -m pip install black

      - run: black .

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs:
      - style
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Fetch Dependabot Metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for patches
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase --delete-branch "${{ github.event.pull_request.html_url }}"
