name: Pull actions

on:
  pull_request:

jobs:
  style:
    runs-on: ubuntu-latest
    name: Check style formatting
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup node.js
        uses: actions/setup-node@v5

      - name: Install dependencies
        run: npm ci

      - name: Validate Pull Request Message
        run: |
          cat << 'EOM' | npx commitlint --verbose --config .commitlintrc.cjs
          ${{ github.event.pull_request.title }}

          ${{ github.event.pull_request.body }}
          EOM

      - name: Validate Commit Messages
        run: |
          npx commitlint \
          --from ${{ github.event.pull_request.base.sha }} \
          --to ${{ github.event.pull_request.head.sha }} \
          --verbose \
          --config .commitlintrc.cjs

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: python3 -m pip install black

      - run: black .

  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    needs:
      - style
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Fetch Dependabot Metadata
        id: dependabot-metadata
        uses: dependabot/fetch-metadata@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Enable auto-merge for patches
        if: ${{ steps.dependabot-metadata.outputs.update-type == 'version-update:semver-patch' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr merge --auto --rebase --delete-branch "${{ github.event.pull_request.html_url }}"
