on:
  push:
    branches:
      - main

name: release
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0
          persist-credentials: false

      - uses: TheRealWaldo/quick-release@v0.4.0
        with:
          token: ${{ secrets.AUTO_PAT }}
          replace-files: custom_components/thermal_vision/const.py,custom_components/thermal_vision/manifest.json
          git-user-email: 68967746+TRW-bot@users.noreply.github.com
          assignees: TheRealWaldo
