on:
  push:
    branches:
      - main

name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: GoogleCloudPlatform/release-please-action@v2
        with:
          release-type: simple
          package-name: pull-request
          changelog-types: >
            [
              { "type": "feat", "section": "Features", "hidden": false },
              { "type": "fix", "section": "Bug Fixes", "hidden": false },
              { "type": "chore", "hidden": true },
              { "type": "docs", "section": "Documentation", "hidden": false },
              { "type": "style", "hidden": true },
              { "type": "refactor", "hidden": true },
              { "type": "perf", "section": "Performance Enhancements", "hidden": false },
              { "type": "test", "hidden": true },
              { "type": "build", "hidden": true },
              { "type": "ci", "hidden": true },
              { "type": "revert", "hidden": true }
            ]
