name: Release

on:
  push:
    branches:
      - main

jobs:
  release-action:
    runs-on: ubuntu-latest
    name: Release action
    if: "github.ref == 'refs/heads/main' && !contains(toJSON(github.event.commits.*.message), 'chore(release)')"
    steps:
      - name: Setup node.js
        uses: actions/setup-node@v2.2.0
        with:
          node-version: 14

      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Install dependencies
        run: npm ci

      - name: Bump version
        id: bump-version
        uses: TheRealWaldo/release-it@v0.3.1
        with:
          github-token: ${{ secrets.AUTO_PAT }}
          github-username: TRW-bot
          git-user-name: TheRealWaldo-bot
          git-user-email: github-bot@inwr.com
          create-branch: release
          rebase-onto: main

      - name: Create pull request
        uses: TheRealWaldo/pull-request@v0.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.AUTO_PAT }}
        with:
          draft: true
          title: "chore(release): ${{steps.bump-version.outputs.version}}"
          body: ${{steps.bump-version.outputs.changelog}}
          base: master
          head: release
          assignee: TheRealWaldo
