name: Validate Actions

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v2.3.5

      - name: Faster HACS validation
        if: "github.base_ref != 'refs/heads/release' && github.ref != 'refs/heads/main'"
        uses: TheRealWaldo/faster-hacs-action@v0.0.4
        with:
          category: integration

      - name: HACS validation
        if: "github.ref == 'refs/heads/main' || (github.ref == 'refs/heads/main' && github.base_ref == 'refs/heads/release')"
        uses: hacs/action@21.2.2
        with:
          category: integration

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
