name: Validate Actions

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v3

      - name: Faster HACS validation
        if: "github.head_ref != 'release' || github.base_ref != 'main'"
        uses: TheRealWaldo/faster-hacs-action@v0.0.6
        with:
          category: integration

      - name: HACS validation
        if: "github.ref == 'main' || (github.base_ref == 'main' && github.head_ref == 'release')"
        uses: hacs/action@22.5.0
        with:
          category: integration

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
