name: Validate Actions

on:
  schedule:
    - cron: "0 0 * * *"
  pull_request:

jobs:
  validate:
    runs-on: ubuntu-latest
    name: Validate
    steps:
      - uses: actions/checkout@v2

      - name: HACS validation
        uses: TheRealWaldo/faster-hacs-action@updates
        with:
          category: integration

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master
